version: '2'
services:
#docker run -d -v /path/to/php/src:/srv -p 2015:2015 abiosoft/caddy:php
#restart
#docker php
    caddy:
        image: abiosoft/caddy:php
        ports:
            -   2015:2015
            -   9000:9000
            -   5001:5001
        volumes:
            - /home/isidoris-simplon/rendu/:/srv
            - ./caddy/Caddyfile:/root/.caddy/Caddyfile
    
    php:
        image: php
        volumes:
        - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - ./php/php.ini:/usr/local/etc/php/php.ini
        - /home/isidoris-simplon/rendu:/var/www/html


    mysql: 
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: wqaxszcde123
            MYSQL_DATABASE: db
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: wqaxszcde123
        ports: 
            - localhost:3306:3306

    # mail:
    #     image: tvial/docker-mailserver:latest
    #     hostname: mail
    #     domainname: sorlin.com
    #     container_name: mail
    #     ports:
    #         - "25:25"
    #         - "143:143"
    #         - "587:587"
    #         - "993:993"
    #     volumes:
    #         - maildata:/var/mail
    #         - mailstate:/var/mail-state
    #         - ./config/:/tmp/docker-mailserver/
    #     environment:
    #         - ENABLE_SPAMASSASSIN=1
    #         - ENABLE_CLAMAV=1
    #         - ENABLE_FAIL2BAN=1
    #         - ENABLE_POSTGREY=1
    #         - ONE_DIR=1
    #         - DMS_DEBUG=0
    #         - ENABLE_LDAP=1
    #         - LDAP_SERVER_HOST=ldap # your ldap container/IP/ServerName
    #         - LDAP_SEARCH_BASE=ou=people,dc=localhost,dc=localdomain
    #         - LDAP_BIND_DN=cn=admin,dc=localhost,dc=localdomain
    #         - LDAP_BIND_PW=admin
    #         - LDAP_QUERY_FILTER_USER="(&(mail=%s)(mailEnabled=TRUE))"
    #         - LDAP_QUERY_FILTER_GROUP="(&(mailGroupMember=%s)(mailEnabled=TRUE))"
    #         - LDAP_QUERY_FILTER_ALIAS="(&(mailAlias=%s)(mailEnabled=TRUE))"
    #         - DOVECOT_PASS_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
    #         - DOVECOT_USER_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
    #         - ENABLE_SASLAUTHD=1
    #         - SASLAUTHD_MECHANISMS=ldap
    #         - SASLAUTHD_LDAP_SERVER=ldap
    #         - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=localhost,dc=localdomain
    #         - SASLAUTHD_LDAP_PASSWORD=admin
    #         - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=localhost,dc=localdomain
    #         - POSTMASTER_ADDRESS=postmaster@localhost.localdomain
    #     cap_add:
    #         - NET_ADMIN
